# version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'


  # nest:
  #   image: node:20
  #   container_name: nest
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   command: sh -c "npm install && npm run start:dev"
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis
  #     - kafka

